package nikkyvi.munifier.tables;

public enum DropEnum {
	BLAZE_POWDER, BLAZE_ROD, GLOWSTONE_DUST, ENDER_PEARL, EMERALD, DIAMOND,
	LAPIS, GHAST_TEAR, QUARTZ, SLIME_BALL, PRISMARINE_CRYSTALS, PRISMARINE_SHARD, 
	NETHER_STAR, GOLD_NUGGET, SILVER_NUGGET, COBALT_NUGGET, ARDITE_NUGGET, ALUBRASS_NUGGET,
	GUNPOWDER, ALUMINIUM_GRIT
}
